class DailyQuote {
  const DailyQuote._();

  static const _ayahs = [
    // 1. Ease, hardship & patience
    _Ayah("فَإِنَّ مَعَ الْعُسْرِ يُسْرًا", "Ash-Sharh 94:5", "With hardship comes ease."),
    _Ayah("إِنَّ مَعَ الْعُسْرِ يُسْرًا", "Ash-Sharh 94:6", "Surely, with hardship comes ease."),
    _Ayah("فَإِذَا فَرَغْتَ فَانصَبْ", "Ash-Sharh 94:7", "When you finish, rise to the next task."),
    _Ayah("وَإِلَىٰ رَبِّكَ فَارْغَب", "Ash-Sharh 94:8", "Turn your longing toward your Lord."),
    _Ayah("وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ", "Al-Baqarah 2:45", "Seek help through patience and prayer."),
    _Ayah("إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", "Al-Baqarah 2:153", "Allah is with the patient."),
    _Ayah("وَبَشِّرِ الصَّابِرِينَ", "Al-Baqarah 2:155", "Give glad tidings to the steadfast."),
    _Ayah("إِنَّمَا يُوَفَّى الصَّابِرُونَ أَجْرَهُم بِغَيْرِ حِسَابٍ", "Az-Zumar 39:10", "The patient are rewarded without measure."),
    _Ayah("وَاصْبِرْ وَمَا صَبْرُكَ إِلَّا بِاللَّهِ", "An-Nahl 16:127", "Be patient; your patience is only through Allah."),
    _Ayah("فَاصْبِرْ إِنَّ الْعَاقِبَةَ لِلْمُتَّقِينَ", "Hud 11:49", "Be patient; the final outcome belongs to the righteous."),
    _Ayah("وَاصْبِرْ لِحُكْمِ رَبِّكَ", "At-Tur 52:48", "Be patient with the decree of your Lord."),
    _Ayah("وَاصْبِرْ عَلَىٰ مَا يَقُولُونَ", "Al-Muzzammil 73:10", "Be patient with what they say."),
    _Ayah("سَيَجْعَلُ اللَّهُ بَعْدَ عُسْرٍ يُسْرًا", "At-Talaq 65:7", "Allah will bring ease after hardship."),
    _Ayah("لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", "Al-Baqarah 2:286", "Allah does not burden a soul beyond its capacity."),
    _Ayah("وَلَا تَهِنُوا وَلَا تَحْزَنُوا", "Ali Imran 3:139", "Do not weaken or grieve."),
    _Ayah("وَأَنتُمُ الْأَعْلَوْنَ إِن كُنتُم مُّؤْمِنِينَ", "Ali Imran 3:139", "You will be superior if you are truly believers."),
    _Ayah("وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ", "Yusuf 12:87", "Do not despair of relief from Allah."),
    _Ayah("إِنَّهُ لَا يَيْأَسُ مِن رَّوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ", "Yusuf 12:87", "None despairs of Allah's mercy except the disbelieving people."),
    _Ayah("وَلَنَبْلُوَنَّكُم بِشَيْءٍ مِّنَ الْخَوْفِ وَالْجُوعِ", "Al-Baqarah 2:155", "We will test you with fear and hunger — give glad tidings to the patient."),
    _Ayah("الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ", "Al-Baqarah 2:156", "To Allah we belong and to Him we return."),
    _Ayah("وَلَمَن صَبَرَ وَغَفَرَ إِنَّ ذَٰلِكَ لَمِنْ عَزْمِ الْأُمُورِ", "Ash-Shura 42:43", "Whoever is patient and forgives — that is truly courageous."),
    _Ayah("وَلَنَجْزِيَنَّ الَّذِينَ صَبَرُوا أَجْرَهُم بِأَحْسَنِ مَا كَانُوا يَعْمَلُونَ", "An-Nahl 16:96", "We will recompense the patient according to the best of what they did."),
    // 2. Tawakkul & trust
    _Ayah("فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ", "Ali Imran 3:159", "When you decide, put your trust in Allah."),
    _Ayah("وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ", "At-Talaq 65:3", "Whoever trusts Allah, He is enough for them."),
    _Ayah("حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", "Ali Imran 3:173", "Allah is enough for us — the best Trustee."),
    _Ayah("وَكَفَىٰ بِاللَّهِ وَكِيلًا", "An-Nisa 4:81", "Sufficient is Allah as a trustee."),
    _Ayah("وَمَا تَوْفِيقِي إِلَّا بِاللَّهِ", "Hud 11:88", "My success is only through Allah."),
    _Ayah("وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَإِنَّ اللَّهَ عَزِيزٌ حَكِيمٌ", "Al-Anfal 8:49", "Whoever trusts Allah — Allah is Mighty, Wise."),
    _Ayah("إِنَّ اللَّهَ يُحِبُّ الْمُتَوَكِّلِينَ", "Ali Imran 3:159", "Allah loves those who put their trust in Him."),
    _Ayah("حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ", "At-Tawbah 9:129", "Sufficient for me is Allah — there is no god but Him."),
    _Ayah("إِنَّ رَبِّي لَطِيفٌ لِّمَا يَشَاءُ", "Yusuf 12:100", "My Lord is subtle in fulfilling what He wills."),
    // 3. Gratitude & shukr
    _Ayah("لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ", "Ibrahim 14:7", "If you are grateful, I will surely increase you."),
    _Ayah("وَإِن تَعُدُّوا نِعْمَةَ اللَّهِ لَا تُحْصُوهَا", "Ibrahim 14:34", "If you count Allah's blessings, you cannot enumerate them."),
    _Ayah("وَمَا بِكُم مِّن نِّعْمَةٍ فَمِنَ اللَّهِ", "An-Nahl 16:53", "Whatever blessing you have, it is from Allah."),
    _Ayah("وَسَخَّرَ لَكُمُ الشَّمْسَ وَالْقَمَرَ", "Ibrahim 14:33", "He has subjected the sun and moon for you."),
    _Ayah("أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ", "Ash-Sharh 94:1", "Did We not expand your chest for you?"),
    _Ayah("فَامْشُوا فِي مَنَاكِبِهَا وَكُلُوا مِن رِّزْقِهِ", "Al-Mulk 67:15", "Walk through the earth and seek His provision."),
    _Ayah("وَاللَّهُ خَيْرُ الرَّازِقِينَ", "Al-Jumuah 62:11", "Allah is the best of providers."),
    _Ayah("وَفِي السَّمَاءِ رِزْقُكُمْ وَمَا تُوعَدُونَ", "Adh-Dhariyat 51:22", "In the sky is your provision and what you are promised."),
    _Ayah("إِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ", "At-Tawbah 9:120", "Allah does not waste the reward of the doers of good."),
    // 4. Knowledge & reflection
    _Ayah("رَّبِّ زِدْنِي عِلْمًا", "Ta-Ha 20:114", "My Lord, increase me in knowledge."),
    _Ayah("إِنَّمَا يَخْشَى اللَّهَ مِنْ عِبَادِهِ الْعُلَمَاءُ", "Fatir 35:28", "Only those with knowledge truly fear Allah."),
    _Ayah("وَفَوْقَ كُلِّ ذِي عِلْمٍ عَلِيمٌ", "Yusuf 12:76", "Above every person of knowledge is one more knowing."),
    _Ayah("إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ لَآيَاتٍ", "Ali Imran 3:190", "In the creation of the heavens and earth are signs for those of understanding."),
    _Ayah("الَّذِينَ يَذْكُرُونَ اللَّهَ قِيَامًا وَقُعُودًا", "Ali Imran 3:191", "Those who remember Allah standing, sitting, and on their sides."),
    _Ayah("رَبَّنَا مَا خَلَقْتَ هَٰذَا بَاطِلًا", "Ali Imran 3:191", "Our Lord, You did not create this in vain."),
    _Ayah("وَفِي الْأَرْضِ آيَاتٌ لِّلْمُوقِنِينَ", "Adh-Dhariyat 51:20", "On earth are signs for those with certainty."),
    _Ayah("وَفِي أَنفُسِكُمْ أَفَلَا تُبْصِرُونَ", "Adh-Dhariyat 51:21", "And within yourselves — will you not then see?"),
    _Ayah("أَفَلَا يَتَدَبَّرُونَ الْقُرْآنَ", "An-Nisa 4:82", "Do they not reflect upon the Quran?"),
    _Ayah("سُبْحَانَكَ لَا عِلْمَ لَنَا إِلَّا مَا عَلَّمْتَنَا", "Al-Baqarah 2:32", "Glory be to You — we have no knowledge except what You taught us."),
    _Ayah("وَمَا أُوتِيتُم مِّنَ الْعِلْمِ إِلَّا قَلِيلًا", "Al-Isra 17:85", "You have been given of knowledge only a little."),
    _Ayah("إِنَّ اللَّهُ عَلِيمٌ خَبِيرٌ", "Al-Hujurat 49:13", "Allah is All-Knowing, All-Aware."),
    // 5. Dhikr & nearness
    _Ayah("فَاذْكُرُونِي أَذْكُرْكُمْ", "Al-Baqarah 2:152", "Remember Me; I will remember you."),
    _Ayah("أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ", "Ar-Rad 13:28", "In the remembrance of Allah hearts find rest."),
    _Ayah("وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ", "Qaf 50:16", "We are closer to him than his jugular vein."),
    _Ayah("وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ", "Al-Baqarah 2:186", "When My servants ask about Me, I am near."),
    _Ayah("ادْعُونِي أَسْتَجِبْ لَكُمْ", "Ghafir 40:60", "Call upon Me; I will respond to you."),
    _Ayah("وَاذْكُرِ اسْمَ رَبِّكَ وَتَبَتَّلْ إِلَيْهِ تَبْتِيلًا", "Al-Muzzammil 73:8", "Remember your Lord and devote yourself to Him."),
    _Ayah("سَبِّحِ اسْمَ رَبِّكَ الْأَعْلَى", "Al-A'la 87:1", "Glorify the name of your Lord, the Most High."),
    _Ayah("فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ", "An-Nasr 110:3", "Glorify the praises of your Lord and ask His forgiveness."),
    _Ayah("وَإِن مِّن شَيْءٍ إِلَّا يُسَبِّحُ بِحَمْدِهِ", "Al-Isra 17:44", "There is nothing that does not glorify His praise."),
    _Ayah("وَبِالْأَسْحَارِ هُمْ يَسْتَغْفِرُونَ", "Adh-Dhariyat 51:18", "In the hours before dawn they would seek forgiveness."),
    _Ayah("يَا أَيُّهَا الَّذِينَ آمَنُوا اذْكُرُوا اللَّهَ ذِكْرًا كَثِيرًا", "Al-Ahzab 33:41", "O believers, remember Allah with much remembrance."),
    _Ayah("وَاذْكُر رَّبَّكَ إِذَا نَسِيتَ", "Al-Kahf 18:24", "Remember your Lord when you forget."),
    // 6. Tawbah & forgiveness
    _Ayah("إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا", "Az-Zumar 39:53", "Allah forgives all sins — He is the Forgiving, the Merciful."),
    _Ayah("قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ", "Az-Zumar 39:53", "O My servants who wronged themselves — do not despair of Allah's mercy."),
    _Ayah("وَهُوَ الَّذِي يَقْبَلُ التَّوْبَةَ عَنْ عِبَادِهِ", "Ash-Shura 42:25", "It is He who accepts repentance from His servants."),
    _Ayah("إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ", "Al-Baqarah 2:222", "Allah loves those who turn to Him in repentance."),
    _Ayah("وَتُوبُوا إِلَى اللَّهِ جَمِيعًا", "An-Nur 24:31", "Turn to Allah together, O believers."),
    _Ayah("وَاسْتَغْفِرُوا رَبَّكُمْ ثُمَّ تُوبُوا إِلَيْهِ", "Hud 11:90", "Seek forgiveness from your Lord and turn to Him."),
    _Ayah("إِنَّ رَبِّي رَحِيمٌ وَدُودٌ", "Hud 11:90", "Indeed my Lord is Most Merciful, Most Loving."),
    _Ayah("وَهُوَ الْغَفُورُ الرَّحِيمُ", "Yunus 10:107", "He is the Most Forgiving, Most Merciful."),
    _Ayah("نَبِّئْ عِبَادِي أَنِّي أَنَا الْغَفُورُ الرَّحِيمُ", "Al-Hijr 15:49", "Tell My servants that I am the Forgiving, the Merciful."),
    _Ayah("وَمَن يَعْمَلْ سُوءًا أَوْ يَظْلِمْ نَفْسَهُ ثُمَّ يَسْتَغْفِرِ اللَّهَ", "An-Nisa 4:110", "Whoever wrongs himself then seeks forgiveness — He is Forgiving, Merciful."),
    _Ayah("فَتَلَقَّىٰ آدَمُ مِن رَّبِّهِ كَلِمَاتٍ فَتَابَ عَلَيْهِ", "Al-Baqarah 2:37", "Adam received words from his Lord, and He relented toward him."),
    _Ayah("إِنَّ الْحَسَنَاتِ يُذْهِبْنَ السَّيِّئَاتِ", "Hud 11:114", "Good deeds erase bad ones."),
    // 7. Striving & deeds
    _Ayah("وَأَن لَّيْسَ لِلْإِنسَانِ إِلَّا مَا سَعَى", "An-Najm 53:39", "A person gains from what they strive for."),
    _Ayah("وَأَنَّ سَعْيَهُ سَوْفَ يُرَىٰ", "An-Najm 53:40", "And that their striving will soon be seen."),
    _Ayah("وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا", "Al-Ankabut 29:69", "Those who strive sincerely are guided to Our ways."),
    _Ayah("وَجَاهِدُوا فِي اللَّهِ حَقَّ جِهَادِهِ", "Al-Hajj 22:78", "Strive in Allah's cause as it deserves."),
    _Ayah("وَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ", "Az-Zalzalah 99:7", "Whoever does an atom's weight of good will see it."),
    _Ayah("قَدْ أَفْلَحَ مَن زَكَّاهَا", "Ash-Shams 91:9", "He has succeeded who purifies it."),
    _Ayah("لِيَجْزِيَهُمُ اللَّهُ أَحْسَنَ مَا عَمِلُوا", "An-Nur 24:38", "Allah rewards the best of what they did."),
    _Ayah("قَدْ أَفْلَحَ الْمُؤْمِنُونَ", "Al-Mu'minun 23:1", "Successful indeed are the believers."),
    _Ayah("كُلٌّ يَعْمَلُ عَلَىٰ شَاكِلَتِهِ", "Al-Isra 17:84", "Each person works according to their own way."),
    _Ayah("وَلْتَنظُرْ نَفْسٌ مَّا قَدَّمَتْ لِغَدٍ", "Al-Hashr 59:18", "Let every soul consider what it has sent ahead for tomorrow."),
    _Ayah("وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ إِلَّا لِيَعْبُدُونِ", "Adh-Dhariyat 51:56", "I created jinn and humans only to worship Me."),
    _Ayah("إِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ مَن أَحْسَنَ عَمَلًا", "Al-Kahf 18:30", "Allah does not waste the reward of one who does good."),
    _Ayah("وَابْتَغِ فِيمَا آتَاكَ اللَّهُ الدَّارَ الْآخِرَةَ", "Al-Qasas 28:77", "Seek the next life through what Allah has given you."),
    _Ayah("وَأَحْسِن كَمَا أَحْسَنَ اللَّهُ إِلَيْكَ", "Al-Qasas 28:77", "Do good just as Allah has been good to you."),
    // 8. Divine decree & change
    _Ayah("إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ", "Ar-Rad 13:11", "Allah changes a people when they change themselves."),
    _Ayah("وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا", "At-Talaq 65:2", "Whoever is mindful of Allah, He makes a way out."),
    _Ayah("وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ", "Al-Baqarah 2:216", "You may dislike something while it is good for you."),
    _Ayah("مَا أَصَابَكَ مِنْ حَسَنَةٍ فَمِنَ اللَّهِ", "An-Nisa 4:79", "Whatever good befalls you is from Allah."),
    _Ayah("لِكُلِّ أَجَلٍ كِتَابٌ", "Ar-Rad 13:38", "For every appointed time there is a written decree."),
    _Ayah("وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ", "Al-Hadid 57:4", "He is with you wherever you are."),
    _Ayah("يُدَبِّرُ الْأَمْرَ مِنَ السَّمَاءِ إِلَى الْأَرْضِ", "As-Sajdah 32:5", "He arranges every matter from the heaven to the earth."),
    _Ayah("مَا يَلْفِظُ مِن قَوْلٍ إِلَّا لَدَيْهِ رَقِيبٌ عَتِيدٌ", "Qaf 50:18", "Not a word is spoken except a watchful observer records it."),
    // 9. Ihsan & character
    _Ayah("وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ", "Ali Imran 3:134", "Allah loves those who do good."),
    _Ayah("وَأَحْسِنُوا إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ", "Al-Baqarah 2:195", "Do good; Allah loves those who do good."),
    _Ayah("وَقُولُوا لِلنَّاسِ حُسْنًا", "Al-Baqarah 2:83", "Speak kindly to people."),
    _Ayah("وَلَا تَنسَوُا الْفَضْلَ بَيْنَكُمْ", "Al-Baqarah 2:237", "Do not forget generosity between you."),
    _Ayah("وَتَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَىٰ", "Al-Maidah 5:2", "Cooperate in righteousness and piety."),
    _Ayah("خُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ", "Al-Araf 7:199", "Be forgiving and command good."),
    _Ayah("وَلَا تَسْتَوِي الْحَسَنَةُ وَلَا السَّيِّئَةُ", "Fussilat 41:34", "Good and evil are not equal — repel evil with what is better."),
    _Ayah("يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللَّهَ", "Al-Hashr 59:18", "O believers, be mindful of Allah."),
    _Ayah("إِنَّ اللَّهَ مَعَ الَّذِينَ اتَّقَوا", "An-Nahl 16:128", "Allah is with those who fear Him and those who do good."),
    _Ayah("وَأَوْفُوا بِالْعَهْدِ إِنَّ الْعَهْدَ كَانَ مَسْئُولًا", "Al-Isra 17:34", "Fulfill your commitments — you will be questioned about them."),
    _Ayah("إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ", "An-Nahl 16:90", "Allah commands justice, good conduct, and generosity."),
    _Ayah("يَا أَيُّهَا الَّذِينَ آمَنُوا لِمَ تَقُولُونَ مَا لَا تَفْعَلُونَ", "As-Saff 61:2", "O believers, why do you say what you do not do?"),
    // 10. Humility & social virtues
    _Ayah("وَعِبَادُ الرَّحْمَٰنِ الَّذِينَ يَمْشُونَ عَلَى الْأَرْضِ هَوْنًا", "Al-Furqan 25:63", "The servants of the Most Merciful walk humbly on earth."),
    _Ayah("وَإِذَا خَاطَبَهُمُ الْجَاهِلُونَ قَالُوا سَلَامًا", "Al-Furqan 25:63", "When the ignorant address them, they say: Peace."),
    _Ayah("إِنَّ أَكْرَمَكُمْ عِندَ اللَّهِ أَتْقَاكُمْ", "Al-Hujurat 49:13", "The most noble of you in Allah's sight is the most righteous."),
    _Ayah("وَلَا تَجَسَّسُوا وَلَا يَغْتَب بَّعْضُكُم بَعْضًا", "Al-Hujurat 49:12", "Do not spy, and do not backbite one another."),
    _Ayah("وَلَا تَصْعَرْ خَدَّكَ لِلنَّاسِ وَلَا تَمْشِ فِي الْأَرْضِ مَرَحًا", "Luqman 31:18", "Do not scorn people, nor walk proudly on earth."),
    _Ayah("وَاغْضُضْ مِن صَوْتِكَ", "Luqman 31:19", "Lower your voice."),
    _Ayah("وَإِذَا مَا غَضِبُوا هُمْ يَغْفِرُونَ", "Ash-Shura 42:37", "When they are angry, they forgive."),
    _Ayah("وَقُل لِّعِبَادِي يَقُولُوا الَّتِي هِيَ أَحْسَنُ", "Al-Isra 17:53", "Tell My servants to say what is best."),
    // 11. Hope & divine promise
    _Ayah("إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ", "Ali Imran 3:9", "Allah never breaks His promise."),
    _Ayah("وَإِنَّ الدَّارَ الْآخِرَةَ لَهِيَ الْحَيَوَانُ", "Al-Ankabut 29:64", "The next life — that is the true life."),
    _Ayah("وَلَلْآخِرَةُ خَيْرٌ لَّكَ مِنَ الْأُولَىٰ", "Ad-Duha 93:4", "The next life is better for you than this one."),
    _Ayah("وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ", "Ad-Duha 93:5", "Your Lord will give to you, and you will be satisfied."),
    _Ayah("أَلَمْ يَجِدْكَ يَتِيمًا فَآوَىٰ", "Ad-Duha 93:6", "Did He not find you an orphan and shelter you?"),
    _Ayah("وَوَجَدَكَ ضَالًّا فَهَدَىٰ", "Ad-Duha 93:7", "And He found you lost and guided you."),
    _Ayah("وَوَجَدَكَ عَائِلًا فَأَغْنَىٰ", "Ad-Duha 93:8", "And He found you poor and made you self-sufficient."),
    _Ayah("وَالْعَاقِبَةُ لِلْمُتَّقِينَ", "Al-Araf 7:128", "The ultimate outcome belongs to the righteous."),
    _Ayah("إِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ مَن أَحْسَنَ عَمَلًا", "Al-Kahf 18:30", "Allah does not waste the reward of one who does good."),
    // 12. Creation & nature
    _Ayah("أَفَلَا يَنظُرُونَ إِلَى الْإِبِلِ كَيْفَ خُلِقَتْ", "Al-Ghashiyah 88:17", "Do they not look at the camels — how they were created?"),
    _Ayah("وَإِلَى السَّمَاءِ كَيْفَ رُفِعَتْ", "Al-Ghashiyah 88:18", "And at the sky — how it was raised?"),
    _Ayah("وَإِلَى الْجِبَالِ كَيْفَ نُصِبَتْ", "Al-Ghashiyah 88:19", "And at the mountains — how they were set firm?"),
    _Ayah("وَإِلَى الْأَرْضِ كَيْفَ سُطِحَتْ", "Al-Ghashiyah 88:20", "And at the earth — how it was spread out?"),
    _Ayah("وَالسَّمَاءَ بَنَيْنَاهَا بِأَيْدٍ وَإِنَّا لَمُوسِعُونَ", "Adh-Dhariyat 51:47", "We built the sky with power — and We are expanding it."),
    _Ayah("وَأَنزَلَ مِنَ السَّمَاءِ مَاءً فَأَحْيَا بِهِ الْأَرْضَ بَعْدَ مَوْتِهَا", "Al-Baqarah 2:164", "He sends rain and revives the earth after its death."),
    _Ayah("وَلَقَدْ كَرَّمْنَا بَنِي آدَمَ", "Al-Isra 17:70", "We have honored the children of Adam."),
    _Ayah("وَجَعَلْنَا مِنَ الْمَاءِ كُلَّ شَيْءٍ حَيٍّ", "Al-Anbiya 21:30", "We made from water every living thing."),
    _Ayah("وَمِنْ آيَاتِهِ اللَّيْلُ وَالنَّهَارُ وَالشَّمْسُ وَالْقَمَرُ", "Fussilat 41:37", "Among His signs are the night and day, the sun and moon."),
    _Ayah("وَسَخَّرَ لَكُم مَّا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ جَمِيعًا", "Al-Jathiyah 45:13", "He subjected for you all that is in the heavens and earth."),
  ];

  static const _quotes = [
    // 1. Focus & single-tasking (40)
    "Focus on the next right action.",
    "Small steps, done daily, become momentum.",
    "Protect your attention; it builds your life.",
    "Clarity first, speed second.",
    "Do the useful thing before the urgent noise.",
    "A calm mind finishes better work.",
    "Today, simplify one thing.",
    "Progress is quiet before it is obvious.",
    "Let purpose choose your priorities.",
    "One completed task beats ten worried thoughts.",
    "Give your best attention to the present task.",
    "Do less, but do it fully.",
    "Make the next step easy to start.",
    "Write it down. Clear the mind.",
    "A focused hour can change the whole day.",
    "Be faithful with the work in front of you.",
    "Finish the tiny promise.",
    "Less distraction, more devotion.",
    "Move with patience and purpose.",
    "The most important task deserves the quietest mind.",
    "Do one thing properly, then the next.",
    "Start before you feel ready.",
    "End the day with one clean completion.",
    "The goal is not busy; the goal is done.",
    "Review yesterday; plan today; trust tomorrow.",
    "Close the loop: start, finish, move on.",
    "Finish the task before you feel tired of it.",
    "Silence is a workspace; guard it.",
    "Deep work is a skill; practice it like one.",
    "The task in front of you is the doorway.",
    "Name the task concretely; vague tasks get postponed.",
    "Inbox zero is not the goal; useful action is.",
    "Batch similar tasks; context switching is expensive.",
    "Two-minute rule: if it takes two minutes, do it now.",
    "Decide once; act many times.",
    "Automate the repeatable; think about the important.",
    "Do the hard useful thing while your mind is fresh.",
    "Today does not need drama; it needs direction.",
    "Keep one promise to yourself before noon.",
    "Reduce the list until action becomes obvious.",

    // 2. Discipline & systems (30)
    "Discipline is remembering what matters.",
    "Consistency carries what motivation starts.",
    "Choose progress over perfection.",
    "Your future is built in today's habits.",
    "Order outside begins with order inside.",
    "Start small. Stay steady.",
    "Begin with gratitude. Continue with discipline.",
    "Let the day have a direction.",
    "Steady work beats anxious planning.",
    "Build systems; moods are unreliable.",
    "The professional shows up; the amateur waits for inspiration.",
    "Mastery is showing up when enthusiasm has left.",
    "Every draft is better than every plan.",
    "You do not rise to your goals; you fall to your systems.",
    "Weekly review is the rudder of the ship.",
    "What gets scheduled gets done.",
    "Peace grows where your actions match your values.",
    "Let your calendar reflect your values.",
    "Plan the week on Sunday; win the week on Monday.",
    "Slow is smooth; smooth is fast.",
    "Quality of effort determines quality of outcome.",
    "Good thinking needs white space on the calendar.",
    "The smallest finished task is real progress.",
    "Strong days are built from honest minutes.",
    "When motivation dips, return to routine.",
    "A clear list turns worry into movement.",
    "Done is better than perfect.",
    "A clean desk is a clear invitation to work.",
    "Make the next step so small that you can begin now.",
    "Done imperfectly beats planned perfectly.",

    // 3. Faith-infused productivity (40)
    "Sabr is strength under control.",
    "Shukr turns today's work into worship.",
    "Make effort, then leave the outcome to Allah.",
    "Good work begins with a clean intention.",
    "A grateful heart works with lighter hands.",
    "Patience is not delay; it is steady movement.",
    "Barakah grows where focus and honesty meet.",
    "Do the task with ihsan: quietly, fully, well.",
    "Trust Allah, then do your part properly.",
    "Let your work be useful, sincere, and steady.",
    "Your attention is an amanah; spend it carefully.",
    "Write it, do it, thank Allah for the ability.",
    "Do not chase every thought; choose the useful one.",
    "A quiet intention can carry heavy work.",
    "Distraction is expensive; focus is barakah.",
    "Niyyah is the seed; amal is the harvest.",
    "Ikhlas purifies the result even when the outcome is small.",
    "Tawakkul is action plus surrender.",
    "Every morning is a new contract with Allah.",
    "Make your private deeds your best deeds.",
    "Character is what you do when no one is watching.",
    "Sincerity in small things is the foundation of large ones.",
    "Fix what you can; accept what you cannot; know the difference.",
    "Be the kind of person who makes rooms calmer.",
    "Gratitude is a perspective shift, not a feeling to wait for.",
    "Resentment is a weight you carry alone.",
    "The body is an amanah; maintain it.",
    "Do good — Allah rewards the best of what you do.",
    "Make effort with your hands and tawakkul with your heart.",
    "The sincere worker is never really alone.",
    "Seek barakah before seeking speed.",
    "Worship is not just prayer — your careful work is worship.",
    "An honest day's work is a form of dhikr.",
    "Begin each task with bismillah and end it with alhamdulillah.",
    "Allah sees your effort even when no one else does.",
    "The believer works as if everything depends on them and prays as if everything depends on Allah.",
    "Riya destroys rewards; ikhlas multiplies them.",
    "Your du'a is your strategy meeting with Allah.",
    "Let your goals be halal and your methods be halal.",
    "Consistency in small acts of worship is beloved to Allah.",

    // 4. Mindset & resilience (35)
    "You cannot pour from an empty cup — rest is productive.",
    "Fear is a compass pointing toward growth.",
    "The obstacle often is the path.",
    "Do not mistake motion for progress.",
    "Difficulty is the price of excellence.",
    "Comparison robs you of the energy to improve.",
    "Your reaction is the only variable you control.",
    "Regret costs more than effort.",
    "The best time to start was yesterday; the second best is now.",
    "Resilience is built from small recoveries.",
    "Humility accelerates learning.",
    "Complaining signals energy; redirect it.",
    "Confidence is built by keeping promises to yourself.",
    "Clarity about values makes choices easier.",
    "A setback is a setup for a stronger comeback.",
    "Growth is not linear; keep going through the plateau.",
    "Fail forward — each mistake carries a lesson.",
    "Pressure reveals character; use it well.",
    "Adversity introduces you to yourself.",
    "The strongest tree grew through the hardest storms.",
    "Equanimity is the superpower of high performers.",
    "Do not let the perfect be the enemy of the good.",
    "Self-awareness is the beginning of self-mastery.",
    "Reframe the problem and the solution often appears.",
    "Ask: what is this teaching me?",
    "Pain is temporary; quitting is permanent.",
    "The mind is a muscle; train it daily.",
    "You are not your worst day.",
    "A negative thought is just that — a thought, not a fact.",
    "Ground yourself in what you can control.",
    "Choose your response, not just your reaction.",
    "The courage to begin is already half the battle.",
    "Discipline is the bridge between goals and accomplishment.",
    "Every expert was once a beginner who kept going.",
    "Breathe. Reset. Continue.",

    // 5. Time & priorities (25)
    "Not everything urgent is important.",
    "Time given to one thing is time taken from another — choose deliberately.",
    "The morning is borrowed; use it before the day claims it.",
    "A boundary around your time is an act of integrity.",
    "Every yes to something is a no to something else.",
    "Energy management matters more than time management.",
    "Rest is not the enemy of productivity; burnout is.",
    "The single most important task of the day — do it first.",
    "If everything is a priority, nothing is.",
    "Say no to the good so you can say yes to the great.",
    "The most powerful word in time management is 'no'.",
    "Guard your mornings like they are sacred — they are.",
    "Time is the one resource you cannot earn back.",
    "Limit your obligations; expand your capacity.",
    "A well-rested brain is more productive than a tired one.",
    "The weekend is for recovery, not just entertainment.",
    "Design your environment to reduce friction toward good work.",
    "The hour before sleep sets the tone for tomorrow.",
    "One deep hour outperforms three scattered ones.",
    "Protect the first two hours of your day from noise.",
    "Value your time and others will value it too.",
    "Urgency is noise; importance is signal.",
    "Live so that the recording of your day is worth watching.",
    "What you do every day matters more than what you do once.",
    "Show up even on the days you do not feel like it.",

    // 6. Spiritual character & virtue (35)
    "A generous word costs nothing and earns much.",
    "Forgive quickly; it is for your peace as much as theirs.",
    "Speak less; listen more; act with care.",
    "Kindness is not weakness — it is the highest strength.",
    "Gratitude rewires the brain toward abundance.",
    "The humble person is always learning.",
    "Seek forgiveness before sleep and wake clean.",
    "Make istighfar a habit, not a response to disasters.",
    "Anger is one letter away from danger — pause.",
    "The tongue can build or break — choose carefully.",
    "Silence at the right moment is wisdom.",
    "Backbiting empties the soul; praise fills it.",
    "Spend time with people who remind you of Allah.",
    "Your circle determines your ceiling.",
    "The most generous are often the most content.",
    "Taqwa is not fear alone — it is conscious awareness.",
    "Envy eats its host; gratitude nourishes.",
    "Protect your heart from what you consume online.",
    "Judge yourself before you judge others.",
    "The sign of a good day: you harmed no one.",
    "Slow down to appreciate the blessings already here.",
    "A moment of reflection is worth an hour of action.",
    "Inner peace is built through outer consistency.",
    "Your deen is your compass; keep it calibrated.",
    "Shyness from wrong is courage disguised as modesty.",
    "The most beloved deeds are the most consistent ones.",
    "A smile is charity — give it freely.",
    "Remove the word 'can't' from du'a — Allah can.",
    "Goodness is in the small, repeated acts of devotion.",
    "Be a source of calm in a noisy world.",
    "Your character is your legacy.",
    "Virtue practiced becomes virtue possessed.",
    "Truthfulness in speech is a pillar of integrity.",
    "Justice begins with being fair to yourself.",
    "Generosity of spirit costs the least and pays the most.",

    // 7. Goals & growth (30)
    "Set the goal, then trust the process.",
    "Ask better questions to get better answers.",
    "The best investment is in your own capacity.",
    "A journal is a conversation with your future self.",
    "Deliberate practice beats passive experience.",
    "Teach to learn; write to think.",
    "The difference between stuck and moving is one small action.",
    "Skills compound like interest — invest early.",
    "Measure progress by who you are, not just what you have.",
    "Learn something new every day; ignorance is optional.",
    "Set intentions, not just goals.",
    "A clear 'why' sustains effort when motivation disappears.",
    "Write down your goals — clarity precedes achievement.",
    "Break the big goal into today's one action.",
    "Track progress; what is measured is managed.",
    "Celebrate small wins — they fuel the next step.",
    "Read more than you scroll.",
    "Knowledge applied is wisdom; knowledge stored is trivia.",
    "Seek feedback — it is the breakfast of champions.",
    "Get comfortable being uncomfortable.",
    "One percent better every day: 37× better in a year.",
    "The expert was once the beginner who kept going.",
    "Curiosity is a superpower — stay curious.",
    "Work on your weaknesses; leverage your strengths.",
    "Vision without action is daydream; action without vision is chaos.",
    "Finish what you start — completion is a habit.",
    "Long-term thinking is a rare and valuable skill.",
    "Your future self will thank your present self for starting.",
    "Don't just set goals — build identity around them.",
    "The only competition that matters is who you were yesterday.",

    // 8. Relationships & community (25)
    "The people around you shape who you become — choose well.",
    "Help someone today; it recalibrates your own perspective.",
    "Generosity in time is rarer than generosity in money.",
    "A good mentor compresses decades into months.",
    "Say thank you more than you think necessary.",
    "Apologise quickly when you are wrong.",
    "Listen to understand, not to respond.",
    "Collaboration is faster than competition.",
    "Build trust through consistency, not promises.",
    "The quality of your relationships is the quality of your life.",
    "Be fully present in conversations — it is rare and valued.",
    "A kind word changes a person's whole day.",
    "Check in on the strong ones — they rarely ask for help.",
    "Give without expectation; receive with gratitude.",
    "Celebrate others' success without diminishing your own.",
    "Be the person who shows up — for others and for yourself.",
    "Strong communities are built through consistent small kindnesses.",
    "Communicate clearly; assume positive intent.",
    "Conflict resolved quickly costs less than conflict avoided.",
    "Loyalty is built through reliability, not words.",
    "Put the phone down when someone is speaking.",
    "Every person carries a story you have not heard.",
    "Reach out to someone you have been meaning to check on.",
    "A shared meal is a shared bond.",
    "Family deserves your best energy, not your leftovers.",

    // 9. Health, body & energy (25)
    "Sleep is the original productivity hack.",
    "Move your body; it clears the mind.",
    "Eat well enough to think clearly.",
    "A walk outside is often the cheapest therapy.",
    "Physical health is moral infrastructure.",
    "Stress without recovery is just damage.",
    "Breathe deeply before a difficult task.",
    "Hydration is a small act with large returns.",
    "Recovery is part of the training.",
    "Your energy levels determine your output quality.",
    "Protect your sleep like you protect your money.",
    "Sunlight in the morning anchors your circadian rhythm.",
    "Exercise is not punishment — it is maintenance.",
    "A ten-minute walk can solve a one-hour problem.",
    "Eat to fuel your purpose, not to escape it.",
    "Chronic stress is a thief of clarity.",
    "Breathwork is the fastest reset available.",
    "Rest proactively rather than collapsing reactively.",
    "Your posture affects your mood — sit tall.",
    "Nature recharges what screens deplete.",
    "Fasting sharpens the mind as well as the soul.",
    "Digital detox is a form of mental hygiene.",
    "A consistent bedtime is one of the best decisions you can make.",
    "Movement is medicine — even five minutes counts.",
    "The body keeps score — listen to it before it shouts.",

    // 10. Creativity & deep work (20)
    "Every draft is better than every plan.",
    "Ship the imperfect; perfect it in the next version.",
    "Constraints breed creativity — work within them.",
    "The best ideas come after the obvious ones are exhausted.",
    "Boredom is the birthplace of creativity.",
    "Work in long blocks; check messages in short bursts.",
    "Put the phone in another room during creative work.",
    "The muse favors those who show up reliably.",
    "Thinking clearly is a skill developed through writing.",
    "A prototype is worth a thousand meetings.",
    "Ship early, iterate often.",
    "Good work requires solitude; great work also requires feedback.",
    "Constraints are not obstacles — they are guardrails.",
    "Produce before you consume each morning.",
    "The second idea is usually better than the first.",
    "Creative blocks dissolve under consistent action.",
    "Inspiration follows perspiration, not the reverse.",
    "Make something every day, no matter how small.",
    "Art is the gift of human beings to each other.",
    "Express yourself — unexpressed creativity turns inward.",

    // 11. Leadership & responsibility (20)
    "Lead by example — actions are louder than titles.",
    "The best leaders make others feel capable, not dependent.",
    "Accountability starts with yourself.",
    "A leader's job is to create more leaders.",
    "Trust is the currency of leadership.",
    "Decision fatigue is real — make important choices early.",
    "Delegate the task; keep the responsibility.",
    "A clear vision energizes a team; ambiguity drains it.",
    "Serve first; authority will follow.",
    "The measure of leadership is the growth of those around you.",
    "Admit mistakes fast and fix them faster.",
    "Praise publicly; correct privately.",
    "Protect your team's focus — interruptions are expensive.",
    "Clarity from the leader is a gift to the team.",
    "People do not leave bad jobs; they leave bad environments.",
    "Invest in people who invest in themselves.",
    "Great leaders ask more questions than they give answers.",
    "A calm leader calms the room.",
    "Model the behavior you want to see.",
    "Responsibility expands to fill the character of the person holding it.",

    // 12. Frugality, contentment & simplicity (20)
    "Contentment with less creates space for more meaning.",
    "The richest person is the one with the fewest unnecessary wants.",
    "Simplify before you optimize.",
    "More stuff rarely solves inner problems.",
    "Buy experiences before possessions.",
    "Debt is borrowed freedom — pay it back.",
    "Live below your means to build above average peace.",
    "Comparison is the thief of contentment.",
    "Enough is a decision, not a destination.",
    "A minimalist environment supports a maximalist mind.",
    "Clutter is postponed decisions — decide now.",
    "Frugality is not poverty; it is intentional abundance.",
    "Zuhd is not owning nothing; it is being owned by nothing.",
    "Gratitude dissolves envy.",
    "The best things in life are not things.",
    "Slow down and notice what is already beautiful around you.",
    "Reduce the want list; appreciate the have list.",
    "Give generously — it creates space for more.",
    "A clean house is a clear mind.",
    "Own your things; do not let your things own you.",

    // 13. Learning & intellectual growth (20)
    "The person who reads daily outlearns the person who studies sporadically.",
    "Every book is a mentor available 24/7.",
    "Take notes — your future self will be grateful.",
    "Summarize what you learn in your own words.",
    "Revisit your notes — reading once is not learning.",
    "Learn across disciplines; connections create breakthroughs.",
    "Be a student first, an expert second.",
    "The smartest people ask the most basic questions.",
    "Understanding trumps memorization.",
    "Teach what you learn within 24 hours of learning it.",
    "Disagree with smart people — it sharpens you.",
    "Seek out those who challenge your assumptions.",
    "Read slowly when the material is dense.",
    "A question asked is intelligence in action.",
    "First principles thinking dissolves complex problems.",
    "The map is not the territory — test your mental models.",
    "Intellectual humility is the gateway to real learning.",
    "If you cannot explain it simply, you do not understand it yet.",
    "Study failures as carefully as successes.",
    "Lifelong learning is the best retirement plan.",

    // 14. Closing wisdom & perspective (30)
    "The day is a gift; spend it intentionally.",
    "Small acts of excellence, repeated, become a life.",
    "Begin again — every hour is a new chance.",
    "The present moment is the only place work actually happens.",
    "Actions speak louder than intentions — but intentions shape actions.",
    "The quality of your questions shapes the quality of your thinking.",
    "Leave every place slightly better than you found it.",
    "What you repeatedly do is what you ultimately are.",
    "Silence your excuses and your hands will find their work.",
    "Be ruthless with time; be generous with people.",
    "Progress over perfection, sincerity over performance.",
    "A life well-planned is a life well-lived — begin with today.",
    "The pen and the task list are more powerful than anxiety.",
    "Make peace with impermanence; make effort with permanence of intention.",
    "If it will not matter in five years, give it five minutes.",
    "You are not defined by your worst day.",
    "The gap between who you are and who you want to be is your work.",
    "Clarity about your one thing eliminates the anxiety of everything.",
    "Today is the future you planned for last year — use it.",
    "Legacy is built one ordinary day at a time.",
    "Character is the sum of your choices when no one is watching.",
    "The most important investment: become someone worth being.",
    "Do not save your best self for special occasions.",
    "Live generously, think deeply, work steadily.",
    "The quietest people often carry the strongest convictions.",
    "Integrity is doing the right thing even when it is costly.",
    "Wisdom is knowing what to overlook.",
    "Happiness follows contribution, not consumption.",
    "Your story is still being written — write it well.",
    "End well — the last impression lingers.",

    // 15. Short, punchy reminders (30)
    "Start.",
    "Finish what you begin.",
    "Do it now.",
    "One more try.",
    "Less talk, more work.",
    "Rest, then rise.",
    "Show up.",
    "Be useful.",
    "Stay consistent.",
    "Calm is productive.",
    "Clarity is kind.",
    "Think first.",
    "Breathe. Then decide.",
    "Slow down to speed up.",
    "Done beats perfect.",
    "Choose the harder right.",
    "Make today count.",
    "Act with intention.",
    "Recover well.",
    "Speak truth kindly.",
    "Serve before you lead.",
    "Give more than you take.",
    "Stay humble.",
    "Keep learning.",
    "Be kind — always.",
    "Eat less worry, more effort.",
    "Fix the process, not the blame.",
    "Less noise, more signal.",
    "Move. Every day.",
    "Tawakkul: do your part, then release.",
  ];

  static String forDate([DateTime? value]) {
    final date = value ?? DateTime.now();
    // Slots change every 2 hours → 12 per day
    final localSlot = DateTime(
      date.year,
      date.month,
      date.day,
      (date.hour ~/ 2) * 2,
    );
    final slot = localSlot.difference(DateTime(2024)).inHours ~/ 2;
    final index = slot.abs();
    final ayah = _ayahs[index % _ayahs.length];
    final quote = _quotes[(index * 17) % _quotes.length];
    return '${ayah.arabic}\n${ayah.reference} — ${ayah.translation}\n\n$quote';
  }
}

class _Ayah {
  const _Ayah(this.arabic, this.reference, this.translation);

  final String arabic;
  final String reference;
  final String translation;
}
